name: master

on:
  push:
    branches:
      - master
      - ci

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip3 install tox tox-docker codecov
    - run: tox
    - run: codecov
